### DISCUSSION TITLE
Local Tests Pass, But Fail on GitHub Actions

### DISCUSSION THREAD

**Discussion by dasundev** [orchestral/testbench-dusk#101] [Q&A]
All tests pass locally, but they fail when running on GitHub Actions.

Result:
```
> ./vendor/bin/pest --parallel
  .⨯
  ────────────────────────────────────────────────────────────────────────────  
   FAILED  Dasundev\PayHere\Tests\Browser\CheckoutTest > i…  TimeoutException   
  timeout: Timed out receiving message from renderer: 10.000
  (Session info: chrome=125.0.6422.60)
  (Driver info: chromedriver=125.0.6422.76 (67dcf7562b8fb4ab08[19](https://github.com/dasundev/laravel-payhere/actions/runs/9186863501/job/25263354881#step:7:20)135589e37a97bcc8942c-refs/branch-heads/6422@{#1086}),platform=Linux 6.5.0-1021-azure x86_64)
  at vendor/php-webdriver/webdriver/lib/Exception/WebDriverException.php:198
    194▕                 throw new XPathLookupException($message, $results);
    195▕             case [20](https://github.com/dasundev/laravel-payhere/actions/runs/9186863501/job/25263354881#step:7:21):
    196▕                 throw new NoSuchCollectionException($message, $results);
    197▕             case [21](https://github.com/dasundev/laravel-payhere/actions/runs/9186863501/job/25263354881#step:7:22):
  ➜ 198▕                 throw new TimeoutException($message, $results);
    199▕             case [22](https://github.com/dasundev/laravel-payhere/actions/runs/9186863501/job/25263354881#step:7:23):
    200▕                 throw new NullPointerException($message, $results);
    201▕             case [23](https://github.com/dasundev/laravel-payhere/actions/runs/9186863501/job/25263354881#step:7:24):
    202▕                 throw new NoSuchWindowException($message, $results);
      +8 vendor frames 
  9   tests/Browser/CheckoutTest.php:22
  Tests:    1 failed, 1 passed (6 assertions)
  Duration: 61.75s
  Parallel: 2 processes
Script ./vendor/bin/pest --parallel handling the test event returned with error code 2
Error: The operation was canceled.
```

**Comment by crynobone** [comment]
https://github.com/laravel/dusk/issues/964#issuecomment-1035973208

**Reply by dasundev** [reply]
@crynobone I've tried without ` --parallel` but it does not work.

**Reply by crynobone** [reply]
Works fine here: https://github.com/orchestral/testbench-dusk/actions

**Reply by dasundev** [reply]
Yeah, I saw that.

Is there something wrong with my `tests.yml` ?

```yaml
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [7, 8, 9, 10, 11]

    name: Test PHP ${{ matrix.php }} with Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --${{ matrix.stability }}

      - name: Create database
        run: php vendor/bin/testbench package:create-sqlite-db

      - name: Start Chrome Driver
        run: vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Tests
        run: composer run test
        env:
          PAYHERE_MERCHANT_ID: ${{ secrets.PAYHERE_MERCHANT_ID }}
          PAYHERE_MERCHANT_SECRET: ${{ secrets.PAYHERE_MERCHANT_SECRET }}
          PAYHERE_APP_ID: ${{ secrets.PAYHERE_APP_ID }}
          PAYHERE_APP_SECRET: ${{ secrets.PAYHERE_APP_SECRET }}
```
