### DISCUSSION TITLE
I get Fatal error: Uncaught Error: Class "P\Tests\Browser\ExampleTest"

### DISCUSSION THREAD

**Discussion by namumakwembo** [orchestral/testbench-dusk#108] [Q&A]
- Testbench Version: "^8.24"
- Laravel Version: "^10.47"
- PHP Version:"^8.1"
- Database Driver & Version: sqlite

### Description:

i get the following error (from error screenshot)when i try to run the test ,Please assist.  Note: i am using pest 

`Fatal error: Uncaught Error: Class "P\Tests\Browser\ExampleOneTest" not found in /Users/yodah/Desktop/Workspace/packages/wirechat/wirechat/vendor/orchestra/testbench-dusk/src/server.php:37 Stack trace: #0 {main} thrown in /Users/yodah/Desktop/Workspace/packages/wirechat/wirechat/vendor/orchestra/testbench-dusk/src/server.php on line 37`

### Steps To Reproduce:

My DuskTestCase

```php

class DuskTestCase extends  \Orchestra\Testbench\Dusk\TestCase

{
    use WithWorkbench; 



    // /**
    //  * Create the RemoteWebDriver instance.
    //  */
    protected function driver(): RemoteWebDriver
    {
        $options = (new ChromeOptions)->addArguments(collect([ '--start-maximized',
        ])->unless($this->hasHeadlessDisabled(), function (Collection $items) {
            return $items->merge([
                '--disable-gpu',
                //'--headless=new',
            ]);
        })->all());

        return RemoteWebDriver::create( 'http://localhost:9515',
            DesiredCapabilities::chrome()->setCapability(
                ChromeOptions::CAPABILITY, $options
            )
        );
    }

    
    protected function getPackageProviders($app)
    {
        return [
          //  ServiceProvider::class,
            LivewireServiceProvider::class,
            MyPackageServiceProvider::class,
            DuskServiceProvider::class
        ];
    }


    protected function setUp(): void
    {
        parent::setUp(); 

        $this->loadMigrationsFrom(
            workbench_path('database/migrations')
        );
        //\Orchestra\Testbench\Dusk\Options::withUI();
        $this->withoutVite();
     

    }
    
    protected function getEnvironmentSetUp($app)
    {


        View ::addLocation('../resources/views');
        tap($app['session'], function ($session) {
            $session->put('_token', str()->random(40));
        });

        tap($app['config'], function ($config) {
            $config->set('app.env', 'testing');

            $config->set('app.debug', true);
            
            //update wirechat userModel
            $config->set('app.debug', true);


            $config->set('view.paths', [__DIR__.'/views', resource_path('views')]);

            $config->set('app.key', 'base64:Hupx3yAySikrM2/edkZQNQHslgDWYfiBfCuSThJ5SK8=');

            $config->set('database.default', 'testbench');

            $config->set('database.default', 'sqlite');
            $config->set('database.connections.testbench', [
                'driver' => 'sqlite',
                'database' => ':memory:',
                'prefix' => '',
            ]);
                      // Setup queue database connections.
                      $config->set('queue.batching.database', 'testbench'); 
                      $config->set('queue.failed.database', 'testbench');
        });
    }

 

 }

```

My testbench.yaml

```yaml
providers:
  - Namu\WireChat\MyPackageServiceProvider

migrations:
  - workbench\database\migrations

seeders:
  - Workbench\Database\Seeders\DatabaseSeeder

#laravel: "./laravel"

workbench:
  start: '/'
  install: true
  user: test@example.com
  discovers:
    web: true
    api: false
    commands: true
    components: true
    views: false
  build: [
    - drop-sqlite-db
    - create-sqlite-db
    - migrate:refresh

  ]
  assets: []
  sync: [
  ]

```
