### DISCUSSION TITLE
Testing with PestPHP

### DISCUSSION THREAD

**Discussion by juliomotol** [orchestral/testbench-dusk#68] [Q&A]
Has anyone tried using this package with PestPHP? It doesn't work for me saying:

```log
FatalError: Uncaught Error: Class "P\Tests\Browser\ExampleTest" was not found in <redacted path>\vendor\orchestra\testbench-dusk\src\server.php:33
```

**Comment by gwleuverink** [comment]
I am experiencing this exact same issue using pest

**Reply by gwleuverink** [reply]
Steps to reproduce:

Consider the following setup

`Pest.php`
``` php
uses(DuskTestCase::class)
    ->group('browser')
    ->in('Browser');
```

`DuskTestCase.php`
``` php
<?php
namespace Leuverink\Bundle\Tests;

use Orchestra\Testbench\Concerns\WithWorkbench;
use Orchestra\Testbench\Dusk\TestCase  as BaseTestCase;

class DuskTestCase extends BaseTestCase
{
    use WithWorkbench;
}
```

The test `tests/Browser/ImportTest.php`
``` php
it('imports from local resource directory')
    ->browse(fn (Browser $browser) => $browser
        ->visit('/test/local-import')
        ->assertDialogOpened('Hello World!')
    );
```

`testbench.yaml`
``` yaml
providers:
  - Workbench\App\Providers\WorkbenchServiceProvider
  - Leuverink\Bundle\ServiceProvider

workbench:
  start: "/"
  install: false
  discovers:
    web: true
    api: false
    commands: false
    components: true
    views: true
  build: []
  assets: []
  sync:
    # Link Bun binary & packages used in testing
    - from: ./workbench/node_modules
      to: ./vendor/orchestra/testbench-core/laravel/node_modules

    # Link local javascript resource dir
    - from: ./workbench/resources/js
      to: ./vendor/orchestra/testbench-core/laravel/resources/js

    # Link config - (problematic, swapped for cp in serve script)
    # - from: ./workbench/jsconfig.json
    #   to: ./vendor/orchestra/testbench-core/laravel
```

## Output
`vendor/bin/pest --group=browser` 

Gives the following output when running `it imports from local resource directory`:

> Fatal error: Uncaught Error: Class "P\Tests\Browser\LocalTest" not found in <redacted-path>/vendor/orchestra/testbench-dusk/src/server.php:37 Stack trace: #0 {main} thrown in <redacted-path>/vendor/orchestra/testbench-dusk/src/server.php on line 37
