### ISSUE TITLE
Laravel 5.7

### ISSUE THREAD

**Issue by Keoghan** [orchestral/testbench-dusk#29]
Been a little busy @crynobone will start getting a 5.7 compatible release together.

**Comment by DarkGhostHunter** [comment]
I tested lightly the master with 5.7 and there was no major problems. Does this pass tests on 5.7.

Also, worth of advice since you 7.3 seems very green right now (there are a couple of important issues, one which affected Facades).

**Comment by sandervanhooft** [comment]
Perhaps we could improve the travis script to enable easier Laravel version testing?

I have had great results rolling a script based on this one here: https://www.tjmiller.me/blog/verifying-laravel-version-compatibility/ .

**Comment by sandervanhooft** [comment]
I'm currently using this script (based on the link above) in a private repo, has saved me a lot of time when upgrading Laravel framework dependencies:

```yml
language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
  - COVERAGE=0
  matrix:
  - LARAVEL='5.5.*' TESTBENCH='3.5.*'
  - LARAVEL='5.6.*' TESTBENCH='3.6.*'
  - LARAVEL='5.7.*' TESTBENCH='3.7.*'

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
  include:
  - php: 7.3
    env: COVERAGE=1 LARAVEL='5.7.*' TESTBENCH='3.7.*'
  exclude:
  - php: 7.3
    env: LARAVEL='5.7.*' TESTBENCH='3.7.*'


before_script:
  - composer config discard-changes true


before_install:
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/support:${LARAVEL}" "illuminate/database:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update


install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest


script:
  - if [[ $COVERAGE = '0' ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE = '1' ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi


after_script:
  - if [[ $COVERAGE = '1' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
```
