### ISSUE TITLE
Uncaught Error when using Pest

### ISSUE THREAD

**Issue by gwleuverink** [orchestral/testbench-dusk#91]
- Testbench Version: ^8.19
- Laravel Version: ^10
- PHP Version: 8.2
- Database Driver & Version: -

### Description:
Previously reported in [this discussion](https://github.com/orchestral/testbench-dusk/discussions/68). 

When running workbench dusk with pest I run into the following error:
> Fatal error: Uncaught Error: Class "P\Tests\Browser\LocalTest" not found in redacted-path/vendor/orchestra/testbench-dusk/src/server.php:37 Stack trace: #0 {main} thrown in redacted-path/vendor/orchestra/testbench-dusk/src/server.php on line 37

### Steps To Reproduce:

Consider the following setup

`Pest.php`
``` php
uses(DuskTestCase::class)
    ->group('browser')
    ->in('Browser');
```

`DuskTestCase.php`
``` php
<?php
namespace Leuverink\Bundle\Tests;

use Orchestra\Testbench\Concerns\WithWorkbench;
use Orchestra\Testbench\Dusk\TestCase  as BaseTestCase;

class DuskTestCase extends BaseTestCase
{
    use WithWorkbench;
}
```

The test `tests/Browser/ImportTest.php`
``` php
it('imports from local resource directory')
    ->browse(fn (Browser $browser) => $browser
        ->visit('/test/local-import')
        ->assertDialogOpened('Hello World!')
    );
```

`testbench.yaml`
``` yaml
providers:
  - Workbench\App\Providers\WorkbenchServiceProvider
  - Leuverink\Bundle\ServiceProvider

workbench:
  start: "/"
  install: false
  discovers:
    web: true
    api: false
    commands: false
    components: true
    views: true
  build: []
  assets: []
  sync:
    # Link Bun binary & packages used in testing
    - from: ./workbench/node_modules
      to: ./vendor/orchestra/testbench-core/laravel/node_modules

    # Link local javascript resource dir
    - from: ./workbench/resources/js
      to: ./vendor/orchestra/testbench-core/laravel/resources/js

    # Link config - (problematic, swapped for cp in serve script)
    # - from: ./workbench/jsconfig.json
    #   to: ./vendor/orchestra/testbench-core/laravel
```

## Output
`vendor/bin/pest --group=browser` 

Gives the following output when running `it imports from local resource directory` inside the browser window (not in cli):

> Fatal error: Uncaught Error: Class "P\Tests\Browser\LocalTest" not found in redacted-path/vendor/orchestra/testbench-dusk/src/server.php:37 Stack trace: #0 {main} thrown in redacted-path/vendor/orchestra/testbench-dusk/src/server.php on line 37
