### ISSUE TITLE
Routes in web.php not available when running browser test cases

### ISSUE THREAD

**Issue by dasundev** [orchestral/testbench-dusk#96]
- Testbench Dusk Version: 8.24
- Laravel Version: 10.0
- PHP Version: 8.2
- Database Driver & Version: SQLite

### Description:
Routes in web.php not available when running browser test cases

### Steps To Reproduce:
I have defined a route in `workbench/routes/web.php`. However, when I run the following test case, it fails and returns a 404 error page in the screenshot.

```php
public function test_render_checkout_page()
{
    $user = User::factory()->create();

    $this->browse(function (Browser $browser) use ($user) {
        $browser->loginAs($user)
            ->visit('/checkout')
            ->screenshot('checkout-page');
    });
}
```
Screenshot:
![checkout-page](https://github.com/orchestral/testbench-dusk/assets/54996800/04f177f7-7c1f-4391-ac72-6f8d1c883d24)

**Comment by crynobone** [comment]
1. Did you import `Orchestra\Testbench\Concerns\WithWorkbench` trait.
2. What's the content of `testbench.yaml`?

**Comment by dasundev** [comment]
1. Yes, I imported the `Orchestra\Testbench\Concerns\WithWorkbench` trait in `tests\DuskTestCase.php`

2. The content of `testbench.yaml`
```yaml
providers:
  - Dasundev\PayHere\PayHereServiceProvider
  - Workbench\App\Providers\WorkbenchServiceProvider

migrations:
  - workbench/database/migrations

seeders:
  - Workbench\Database\Seeders\DatabaseSeeder

workbench:
  welcome: true
  install: true
  start: '/'
  discovers:
    web: true
  build:
    - create-sqlite-db
    - migrate:fresh
    - db:seed
```
